import { Inter, Caveat } from "next/font/google"
import "./globals.css"
import Header from "@/components/header"
import Footer from "@/components/footer"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
})

const caveat = Caveat({
	subsets: ["latin"],
	variable: "--font-caveat",
})

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${caveat.variable} flex items-center flex-col gap-20`}
				style={{
					display: "flex",
					alignItems: "center",
					flexDirection: "column",
				}}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}

export default RootLayout
